contact_store:
  path:     /api/v1/contacts
  controller: App\Controller\Api\v1\ContactController::store

contact_index:
  path:     /contacts
  controller: App\Controller\Web\ContactController::index